# Generated by Django 5.1 on 2024-08-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmueble',
            old_name='comunas',
            new_name='comuna',
        ),
    ]
